### ISSUE TITLE
add stat test of different models

### ISSUE THREAD

**Issue by anaderi** [yandexdataschool/modelgym#15]

**Comment by Boialex** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [добавить сравнение roc_auc-ов](https://trello.com/c/IHVmZSA0/1-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D1%81%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5-rocauc-%D0%BE%D0%B2)
