### ISSUE TITLE
run modelgym with docker

### ISSUE THREAD

**Issue by andreiSaw** [yandexdataschool/modelgym#25]
i runned a container and tried to run `model_search.ipynb ` and get an error 
![screen shot 2017-11-09 at 02 51 21](https://user-images.githubusercontent.com/18559300/32581104-875e4154-c4f9-11e7-8cdb-9eea653aafff.png)
maybe an outdated version is installed in /src

**Comment by anaderi** [comment]
fixed at a6b190f520ae023b004ba7b2def670c4538189b9
