### ISSUE TITLE
Add an option for hardcoding model paramters

### ISSUE THREAD

**Issue by kazeevn** [yandexdataschool/modelgym#45]
Usually it's desirable to pass some parameters directly to the model class. I'm using this workaround, but it might be not the most elegant way.
```
catboost_space = {
    'iterations': hp.choice('iterations', [100]),
    'task_type': hp.choice('task_type', ["GPU"])
```

**Comment by bamasa** [comment]
To **fix parameters** use Categorical with one category for skopt

```python
xgboost_space = [
    Categorical([10], name='max_depth'),
]
```
and just a value for hyperopt

```python
xgboost_space = {
    'max_depth': 10,
}
```

**Comment by bamasa** [comment]
Last updates are available [here](https://github.com/wonderlandcompute/modelgym).

**Comment by anaderi** [comment]
Seems like this one is closed.
